### PR TITLE
Avoid conflation of documents-publishing and console-publishing.

### PR DESCRIPTION
**Pull request by danielballan**
Renamed CLI parameters of `start-re-manager`:

- `--zmq-publish` is renamed to `--zmq-publish-console`
- `--zmq-publish-addr` is renamed to `--zmq-publish-console-addr`

### CODE REVIEW

**Comment by dmgav** [comment]
I think changes to parameter are reasonable, except that the parameter names may become too long. Setting `det.kind` in the simulated startup files is fine, but there should be some comment on why it is needed here and where it is used, otherwise nothing prevents someone from deleting it in the future (CI will still pass).

Also, since command parameters are changed, tests and documentation needs to be updated accordingly. I probably can update it later.

**Comment by danielballan** [comment]
Oops, I didn't mean to commit the `det.kind` change. I think we should _not_ commit that actually go ahead with a separate profile.

**Comment by danielballan** [comment]
I am also happy to clean this up myself after I return from vacation if you don't get to it first.

**Comment by dmgav** [comment]
I think I made all necessary changes. The PR is ready to be merged.

**Pull request merged**
