### PR TITLE
FIX: reject create/close environment requests if already underway

### PR DESCRIPTION
**Pull request by developingAlex**
Make use of the RE Manager MState enum to indicate when the
manager is already underway in the creation or closing of a
RE Worker environment.

Previously the manager would get into a locked up state if
a request to create an environment was received while it was
already mid-way through the act of creating an environment.

### CODE REVIEW

**Comment by dmgav** [comment]
@developingAlex Thank you. I will take a closer look at the code later today or tomorrow morning. CI is failing most likely because there are compatibility issues with `pyzmq` 20.0.0. I was planning to look at it later today or tomorrow.

**Comment by developingAlex** [comment]
Hey I'm not sure if it was my changes that are causing the failing unit tests (forgot to check before opening the pull request), so I'm trying to run the unit tests on my machine, but firstly trying to check they all pass without my changes and at the [current commit](https://github.com/bluesky/bluesky-queueserver/commit/a442253fe2b2600a565910e861584054bb87eea6) where you merged in your fix for pyzmq version, but I'm still getting failing tests (which is in contrast to [the last check run](https://github.com/bluesky/bluesky-queueserver/actions/runs/371077619) that seems to be all good), and they seem to be from a mismatch between loaded plans and devices vs those on file.
And in following that thread I learned that you have a CLI tool that generates the file if I understand correctly, but when I look at [the relevant line](https://github.com/bluesky/bluesky-queueserver/blob/a442253fe2b2600a565910e861584054bb87eea6/setup.py#L51) in setup.py to establish it as an entrypoint it looks like maybe it's incomplete since it doesn't end with a colon (what I guess is a function reference) like the other lines do? 
Here's one of the relevant errors I get when running the test_profile_ops:
```
E               FileNotFoundError: [Errno 2] No such file or directory: 'qserver_list_of_plans_and_devices': 'qserver_list_of_plans_and_devices'

/usr/lib/python3.7/subprocess.py:1551: FileNotFoundError
```
and this is what the test summary prints:
```
==================================== short test summary info =====================================
FAILED manager/tests/test_profile_ops.py::test_verify_default_profile_collection - AssertionErr...
FAILED manager/tests/test_profile_ops.py::test_gen_list_of_plans_and_devices_cli[incorrect_path-1]
FAILED manager/tests/test_profile_ops.py::test_gen_list_of_plans_and_devices_cli[specify_path-0]
FAILED manager/tests/test_profile_ops.py::test_gen_list_of_plans_and_devices_cli[default_path-0]
=========================== 4 failed, 111 passed, 35 warnings in 6.72s ===========================
```
I'm just not sure if there's something I might be doing wrong on my end or some thing I was meant to do before running the tests?

**Comment by dmgav** [comment]
@developingAlex The `setup.py` file looks fine to me. The string that defines the entry point is split in two parts so it looks strange. But it seems to work fine. Have you tried to reinstall the queueserver? 

We didn't mention `qserver_list_of_plans_and_devices` in the documentation yet. It needs to be executed in the directory that contains the profile collection to generate the file that contains the list of available plans and devices. The repository already contains the list of plans and devices in `profile_collection_sim` directory. There is no need to manually generate the new list if the profile collection, built-in bluesky plans or the code that generates the file change. But one of the tests verifies that the file is up-to-date and `qserver_list_of_plans_and_devices` is functional.

Can you rebase your branch to the main branch of the repository and push the changes? It is likely that CI will just pass.

**Comment by developingAlex** [comment]
Thanks @dmgav  for the suggestion to reinstall the queueserver, I forgot about that, I've managed to confirm that it is my changes that are breaking some tests and have managed to get a fresh copy to have all tests pass without my changes, I will close this PR and open another one later from a different branch

**Pull request closed without merging**
