### PR TITLE
FIX: add a lock around zmq access

### PR DESCRIPTION
**Pull request by tacaswell**
Serialize access to zmq socket from web requests

### CODE REVIEW

**Review by cryos — APPROVED** [review]
This fixes the failures I was seeing in my local development environment.

**Review by mrakitin — APPROVED** [review]
This worked for me very well!

**Comment by dmgav** [comment]
The problem is that I rewrote this code substantially. My fix is exactly the same, but there are more changes, e.g. the socket is automatically reopened in case of failure.

**Comment by tacaswell** [comment]
Closed because @dmgav has fixed this else where.

**Pull request closed without merging**
