### PR TITLE
Basic tutorials (Documentation)

### PR DESCRIPTION
**Pull request by dmgav**
The PR includes a few tutorials that are demonstrating basic features of Queue Server. I am planning to write another set of 'advanced' tutorials to demonstrate less obvious features.

The best way to read the tutorials is to built HTML by running ` make -C docs/ html`.

**For reviewers.** It is best to split the comments into two categories: comments on how to improve the tutorials in this PR so that they could be merged and published and suggestions on what topics to cover in additional basic tutorials and documentation and how to expand the existing outline.

### CODE REVIEW

**Comment by whs92** [comment]
**Comments on the tutorial in this PR:**

It's definitely readable and covers the basics well. I think it would be good to include a diagram to show how the queserver fits in with the other parts of Bluesky. You already state clearly what qserver is and what it is not, but I still found this difficult to get my head around when I started using this. In the internal documentation we use we have this diagram, maybe somthing like it would be useful here. I think this is generally a problem with Bluesky documentation that it by design allows the user to configure the system exactly how they want, but there is often a kind of "serving suggestion" missing.

image

**Suggestions for future tutorials:**

You've already covered the other areas I am interested in in the existing docs. Namely [permissions](https://blueskyproject.io/bluesky-queueserver/features_and_config.html) and [plan_annotation](https://blueskyproject.io/bluesky-queueserver/plan_annotation.html)

I will of course also be interested in the IPython API when it's available, and I'd welcome an example of how to run the queueserver as a service. There are lots of ways of doing this, but again I think it would be useful to have a suggestion of best practice.

**Review by whs92 — COMMENTED** [review]
**Comments on the tutorial in this PR:**

It's definitely readable and covers the basics well. I think it would be good to include a diagram to show how the queserver fits in with the other parts of Bluesky. You already state clearly what qserver is and what it is not, but I still found this difficult to get my head around when I started using this. In the internal documentation we use we have this diagram, maybe somthing like it would be useful here. I think this is generally a problem with Bluesky documentation that it by design allows the user to configure the system exactly how they want, but there is often a kind of "serving suggestion" missing.

image

**Suggestions for future tutorials:**

You've already covered the other areas I am interested in in the existing docs. Namely [permissions](https://blueskyproject.io/bluesky-queueserver/features_and_config.html) and [plan_annotation](https://blueskyproject.io/bluesky-queueserver/plan_annotation.html)

I will of course also be interested in the IPython API when it's available, and I'd welcome an example of how to run the queueserver as a service. There are lots of ways of doing this, but again I think it would be useful to have a suggestion of best practice.

**Comment by prjemian** [comment]
Getting started reading through the tutorial, following the steps.  Very helpful guidance so far.

**Comment by prjemian** [comment]
In the tutorial here at line 90:
image

what does the word *False* indicate here?

**Comment by prjemian** [comment]
@whs92: I like the workflow diagram you contributed and suggest it (or something like it) be used int he documentation.  For the different parts of the the tutorial, the specific path through the workflow can be highlighted.  This will improve understanding.

**Review by prjemian — CHANGES_REQUESTED** [review]
Clarify the item about *False* that I mentioned.  Then, LGTM!

**Pull request merged**
