### PR TITLE
Proof-of-Principle Prototype of the QueueServer that Manages and Executes the Queue via REST API

### PR DESCRIPTION
**Pull request by dmgav**
This is the proof-of-principle prototype of the QueueServer that implements the following functions:

- management of the queue (add element, remove (pop) last (not first) element, get queue info, read queue);

- creation and initialization, and closing (destruction) of the execution environment (worker process) for Bluesky Run Engine;

- execution of the queue; additional plans may be added while the queue is running executed,

- pausing (immediate and deferred) of running plan (and the queue), resuming, aborting, stopping and halting of the paused plan. If the plan is resumed, execution of the queue is resumed (next plan will be executed once the current plan is completed). If the plan is aborted, stopped or halted, execution of the queue is stopped and the current plan remains in the queue. Queue can be restarted at any time.

- some basic error handling is added; error messages are printed in the terminal in which the server is run.

- collection of data to 'temp' Databroker; REST API to list UIDs of collected runs (this is demo-only feature).

What is missing:

- comprehensive error handling and reporting (currently error messages are printed in the terminal running QueueServer;

- monitoring of Run Engine status while a plan is executed (in the demo the BEC table is printed on the terminal that runs the server, but if you have only REST API access you have to hope for the best).

### CODE REVIEW

**Comment by tacaswell** [comment]
We need to turn off the code-cov bot...

**Comment by dmgav** [comment]
Now it seems to me that `subprocess` may be a better choice. I will try to rewrite the code using subprocesses.

**Comment by dmgav** [comment]
After the last two commits the server supports pausing (immediate and deferred), resuming, aborting, stopping and halting the plans using REST API commands. There is also some basic error handling implemented.

**Comment by dmgav** [comment]
New demo feature: collection to 'temp' Databroker.

**Comment by tacaswell** [comment]
Discussed this on a call with @MikeHart85  and @dmgav, merging and will iterate in future PRs.

**Pull request merged**
